# Generated by Django 4.2.2 on 2023-06-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0002_alter_projects_project_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="username",
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
