# Generated by Django 4.2.2 on 2023-06-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_remove_users_username_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributors",
            name="permission",
            field=models.CharField(
                choices=[("C", "Complete"), ("L", "Limitée")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="contributors",
            name="role",
            field=models.CharField(
                choices=[("A", "Auteur"), ("C", "Contributeur")], max_length=1
            ),
        ),
    ]
