# Generated by Django 4.2.2 on 2023-07-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0004_alter_contributors_permission_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contributors",
            unique_together={("contributors_user_id", "contributors_project_id")},
        ),
    ]
